export const Languages: Languages = {
  af: 'Afrikaans',
  ar: 'Arabic',
  az: 'Azerbaijani',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bn: 'Bengali',
  ca: 'Catalan',
  cs: 'Czech',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Frisian',
  ga: 'Irish',
  gd: 'Scots Gaelic',
  gl: 'Galician',
  gu: 'Gujarati',
  ha: 'Hausa',
  haw: 'Hawaiian',
  he: 'Hebrew',
  hi: 'Hindi',
  hmn: 'Hmong',
  hr: 'Croatian',
  ht: 'Haitian Creole',
  hu: 'Hungarian',
  id: 'Indonesian',
  ig: 'Igbo',
  is: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  jw: 'Javanese',
  ka: 'Georgian',
  kk: 'Kazakh',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  ku: 'Kurdish',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lo: 'Lao',
  lt: 'Lithuanian',
  lv: 'Latvian',
  mg: 'Malagasy',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  ne: 'Nepali',
  nl: 'Dutch',
  no: 'Norwegian',
  ny: 'Nyanja',
  pa: 'Punjabi',
  pl: 'Polish',
  ps: 'Pashto',
  pt: 'Portuguese',
  ro: 'Romanian',
  ru: 'Russian',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  st: 'Sesotho',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  tl: 'Filipino',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  'zh-CN': 'Chinese Simplified',
  'zh-TW': 'Chinese Traditional',
  zu: 'Zulu',
};

export interface Languages {
  'af': 'Afrikaans';
  'sq': 'Albanian';
  'ar': 'Arabic';
  'az': 'Azerbaijani';
  'eu': 'Basque';
  'bn': 'Bengali';
  'be': 'Belarusian';
  'bg': 'Bulgarian';
  'ca': 'Catalan';
  'zh-CN': 'Chinese Simplified';
  'zh-TW': 'Chinese Traditional';
  'hr': 'Croatian';
  'cs': 'Czech';
  'da': 'Danish';
  'nl': 'Dutch';
  'en': 'English';
  'eo': 'Esperanto';
  'et': 'Estonian';
  'tl': 'Filipino';
  'fi': 'Finnish';
  'fr': 'French';
  'fy': 'Frisian';
  'gl': 'Galician';
  'ka': 'Georgian';
  'de': 'German';
  'el': 'Greek';
  'gu': 'Gujarati';
  'ht': 'Haitian Creole';
  'ha': 'Hausa';
  'haw': 'Hawaiian';
  'he': 'Hebrew';
  'hi': 'Hindi';
  'hmn': 'Hmong';
  'hu': 'Hungarian';
  'is': 'Icelandic';
  'ig': 'Igbo';
  'id': 'Indonesian';
  'ga': 'Irish';
  'it': 'Italian';
  'ja': 'Japanese';
  'jw': 'Javanese';
  'kn': 'Kannada';
  'kk': 'Kazakh';
  'km': 'Khmer';
  'ko': 'Korean';
  'ku': 'Kurdish';
  'ky': 'Kyrgyz';
  'lo': 'Lao';
  'la': 'Latin';
  'lv': 'Latvian';
  'lt': 'Lithuanian';
  'lb': 'Luxembourgish';
  'mk': 'Macedonian';
  'mg': 'Malagasy';
  'ms': 'Malay';
  'ml': 'Malayalam';
  'mt': 'Maltese';
  'mi': 'Maori';
  'mr': 'Marathi';
  'mn': 'Mongolian';
  'my': 'Burmese';
  'ne': 'Nepali';
  'no': 'Norwegian';
  'ny': 'Nyanja';
  'ps': 'Pashto';
  'pl': 'Polish';
  'pt': 'Portuguese';
  'pa': 'Punjabi';
  'ro': 'Romanian';
  'ru': 'Russian';
  'sm': 'Samoan';
  'gd': 'Scots Gaelic';
  'sr': 'Serbian';
  'st': 'Sesotho';
  'sn': 'Shona';
  'sd': 'Sindhi';
  'si': 'Sinhala';
  'sk': 'Slovak';
  'sl': 'Slovenian';
  'so': 'Somali';
  'es': 'Spanish';
  'su': 'Sundanese';
  'sw': 'Swahili';
  'sv': 'Swedish';
  'tg': 'Tajik';
  'ta': 'Tamil';
  'te': 'Telugu';
  'th': 'Thai';
  'tr': 'Turkish';
  'uk': 'Ukrainian';
  'ur': 'Urdu';
  'uz': 'Uzbek';
  'vi': 'Vietnamese';
  'cy': 'Welsh';
  'xh': 'Xhosa';
  'yi': 'Yiddish';
  'yo': 'Yoruba';
  'zu': 'Zulu';
  [key: string]: string;
}

export type Language = Languages[keyof Languages];
export type LanguageCode = keyof Languages;
